#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Stopping shutdown listener...\n"
sudo update-rc.d handle_power_button.sh remove
sudo /etc/init.d/handle_power_button.sh stop

echo "=> Removing shutdown listener...\n"
sudo rm -rf /usr/local/bin/handle_power_button.py
sudo rm -rf /etc/init.d/handle_power_button.sh

echo "Shutdown listener uninstalled.\n"
echo "Check out howchoo.com for more awesome Pi projects!"
