#!/bin/sh

set -e

REPO_DIR="$(dirname "$0")/.."

SCRIPT_DIR="/usr/local/lib/power_button"
SCRIPT_NAME="power_button.py"
SERVICE_NAME="power_button.service"
SERVICE_DIR="/lib/systemd/system"

printf "=> Installing power button service...\n"

# Script
mkdir -p "${SCRIPT_DIR}"
cp "${REPO_DIR}/${SCRIPT_NAME}" "${SCRIPT_DIR}"
chmod +x "${SCRIPT_DIR}/${SCRIPT_NAME}"

# Systemd unit
cp "${REPO_DIR}/${SERVICE_NAME}" "${SERVICE_DIR}"
chown root:root "${SERVICE_DIR}/${SERVICE_NAME}"
chmod 644 "${SERVICE_DIR}/${SERVICE_NAME}"

printf "=> Enabling and starting power button service...\n"
systemctl enable --now power_button.service

printf "=> Power button service installed...\n"
