#!/bin/sh

set -e

REPO_DIR=$(dirname "$0")

SCRIPT_DIR="/usr/local/lib/power_button"
SCRIPT_NAME="power_button.py"
SERVICE_NAME="power_button.service"

printf "=> Installing power button service...\n"

# Script
mkdir -p "${SCRIPT_DIR}"
cp "${REPO_DIR}/${SCRIPT_NAME}" "${SCRIPT_DIR}"
chmod +x "/usr/local/lib/${SCRIPT_NAME}"

# Systemd unit
cp "${REPO_DIR}/${SERVICE_NAME}" /etc/init.d/
chown root:root "/etc/init.d/${SERVICE_NAME}"
chmod 644 "/etc/init.d/${SERVICE_NAME}"

printf "=> Enabling and starting power button service...\n"
systemctl enable --now power_button.service

printf "=> Power button service installed...\n"
