#! /bin/sh

set -e

SCRIPT_DIR="/usr/local/lib/power_button"
SERVICE_NAME="power_button.service"

cd "$(dirname "$0")/.."

printf "=> Stopping and disabling power button service...\n"
systemctl disable --now power_button.service

printf "=> Uninstalling power button service...\n"
# Systemd unit
rm -f "/etc/init.d/${SERVICE_NAME}"
# Script
rm -rf "${SCRIPT_DIR}"

printf "=> Power button service uninstalled...\n"
